
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}]
};

module.exports = sidebars;

// module.exports = {
//   tutorialSidebar: [
//     'introduction',
//     {
//       type: 'category',
//       label: 'Guide',
//       items: [
//         { type: 'doc', label: '客户端技术', id: 'guide/app' },
//         { type: 'doc', label: '成长体系', id: 'guide/others' }
//       ]
//     }
//   ]
// }
